print("Day 1- Python Print Function")
print("The function is declared like this:")
print("print( 'what to print' )")
print("Day 1- Python Print Function\nThe functio is declared like this:\nprint( 'what to print' )")
print("Day 1- Python Print Function\nThe functio is declared like this:\nprint( 'what to print' )")